version: "3.7"

services:
  influx:
    build: docker/influx
    image: influx
    ports:
      - "8086:8086"

  pgdb:
    build: docker/postgres
    image: pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pg_password

  shell:
    build: docker/shell
    image: shell
    volumes:
      - ./consumer:/consumer
      - ./producer:/producer
    environment:
      # Contant Logan Vining, the owner of this repo, for the organization name
      # & API Token if you would like to run this system and write data to
      # InfluxDB
      - INFLUX_ORG=<placeholder_org>
      - INFLUX_BUCKET=hydrograph_time_series
      - INFLUX_TOKEN=<secret_token>

  pg_client:
    depends_on:
      - pgdb
    build: docker/pg_client
    image: pg_client
    volumes:
      - ./pg_commands:/commands
