version: "3.7"

services:
  pgdb:
    build: docker/postgres
    image: pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pg_password

  shell:
    build: docker/shell
    image: shell
